// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/user": {
            "post": {
                "description": "Создает нового пользователя либо по telegram_id либо по email",
                "summary": "Создание нового пользователя",
                "responses": {}
            }
        },
        "/api/user/:id": {
            "get": {
                "summary": "Получение пользователя по Id",
                "responses": {}
            },
            "put": {
                "description": "Обновляет поля пользовател",
                "summary": "Обновление пользователя",
                "responses": {}
            }
        },
        "/login": {
            "post": {
                "description": "Вход через Телеграм или через почту. Создает пользователя, если его нет",
                "summary": "Аутентификация",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
